In [2]:
import pandas as pd
import geopandas as gpd
import fiona
import numpy as np
import requests

This script starts from the list of fire we want to vaidate and sends of all the requests to the API

In [11]:
calfire_filtered_parks = gpd.read_file("Validation_Fire_Perimeters_2015_2024.shp")
calfire_filtered_parks.head()

,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,C_METHOD,OBJECTIVE,GIS_ACRES,COMMENTS,COMPLEX_NA,IRWINID,FIRE_NUM,COMPLEX_ID,DECADES,geometry
0,2024,CA,NPS,KNP,COFFEE POT,00000088,2024/08/03 00:00:00,2024/12/16 00:00:00,1,3,1,14103.9000,None,None,{62A5DB78-38A8-4B54-8F7C-664DB0783E9C},None,None,2020-January 2025,"MULTIPOLYGON (((-13217941.346 4353257.821, -13..."
1,2024,CA,NPS,KNP,SENTINEL,00000058,2024/07/14 00:00:00,2024/11/08 00:00:00,14,7,1,260.6600,None,None,{5656FBF0-3D2E-4221-BA42-39E7723EC166},None,None,2020-January 2025,"POLYGON ((-13208263.579 4405096.209, -13208266..."
2,2024,CA,NPS,KNP,SIMPSON,00000074,2024/07/26 00:00:00,2024/09/02 00:00:00,14,2,1,52.1125,None,None,{65AA08F3-7325-4D42-8457-A6F0E12230AB},None,None,2020-January 2025,"POLYGON ((-13204355.841 4436805.636, -13204311..."
3,2023,CA,NPS,MNP,YORK,00010701,2023/07/28 00:00:00,2023/08/20 00:00:00,14,7,1,93077.9000,None,None,{B9E0F397-DE63-4B90-B5DA-9D04A7D2381B},None,None,2020-January 2025,"POLYGON ((-12815785.524 4224752.868, -12815785..."
4,2023,CA,NPS,KNP,REDWOOD,00000061,2023/08/15 00:00:00,2023/12/14 00:00:00,1,7,2,2248.4500,None,None,{405281C7-2B67-43C1-8F7A-F907AE53D92E},None,None,2020-January 2025,"POLYGON ((-13205607.284 4375004.509, -13205597..."

### Define functions

In [16]:

def create_bbox(fire_name, fires):
    ''' creates a buffered bounding box around a fire parameter '''

    fire = fires[fires['FIRE_NAME'] == fire_name].buffer(250).to_crs(epsg=4326)
    
    bbox = fire.bounds

    return bbox

def get_fire_date(fire_name, fires):
    ''' gets the alarm (start) date of a fire '''

    start_date = pd.to_datetime(fires[fires['FIRE_NAME'] == fire_name]['ALARM_DATE'].values[0]).to_datetime64()

    return start_date

def get_cont_date(fire_name, fires):
    ''' gets the containment date of a fire, returns None if missing '''

    raw = fires[fires['FIRE_NAME'] == fire_name]['CONT_DATE'].values[0]

    if pd.isnull(raw):
        return None

    return pd.to_datetime(raw).to_datetime64()

def create_query(fire_name, bbox, date_of_fire, post_fire_range, date_mode='alarm'):
    ''' Creates an API query for the bounding box and time period specified.
    
    date_mode: 'alarm' or 'cont' — recorded in the fire_event_name for downstream tracking.
    '''

    pre_start = date_of_fire - np.timedelta64(21, 'D')
    pre_end = date_of_fire - np.timedelta64(1, 'D')
    post_end = date_of_fire + np.timedelta64(post_fire_range, 'D')

    api_request = {
        "fire_event_name": f"{fire_name}_date{str(date_of_fire).split('T')[0]}_range{post_fire_range}_mode{date_mode}",
        "coarse_geojson": {
            "type": "Polygon",
            "coordinates": [[
                [float(bbox[0]), float(bbox[1])], 
                [float(bbox[2]), float(bbox[1])],
                [float(bbox[2]), float(bbox[3])], 
                [float(bbox[0]), float(bbox[3])], 
                [float(bbox[0]), float(bbox[1])]  
            ]]
        },
        "prefire_date_range": [str(pre_start).split('T')[0], str(pre_end).split('T')[0]],
        "postfire_date_range": [str(date_of_fire).split('T')[0], str(post_end).split('T')[0]]
    }
   
    return api_request

### Test if it works

In [17]:
url = "https://fire-recovery-backend-dev-113009620257.us-central1.run.app/fire-recovery/process/analyze_fire_severity" 

fire_name = 'YORK'
bbox = create_bbox(fire_name, calfire_filtered_parks)
date_of_fire = get_fire_date(fire_name, calfire_filtered_parks)
query_data = create_query(fire_name, bbox.values[0], date_of_fire, 15)
try:
    # Use the 'json' parameter: it automatically sets 'Content-Type: application/json'
    # and runs json.dumps() for you.
    response = requests.post(url, json=query_data)

    # 4. Check the results
    if response.status_code == 200 or response.status_code == 201:
        print("Success!")
        print(response.json()) # This is the data the API sends back
    else:
        print(f"Failed with status code: {response.status_code}")
        print(response.text) # This shows the error message from the API

except requests.exceptions.RequestException as e:
    print(f"A connection error occurred: {e}")

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

Success!
{'fire_event_name': 'YORK_date2023-07-28_range15_modealarm', 'status': 'Processing started', 'job_id': '8536bc78-ed44-4bc6-a1bd-22aa0b02dff7'}

In [18]:
# Get list of fire names to process
fire_names = calfire_filtered_parks['FIRE_NAME'].unique()

# Define post-fire day ranges to test
post_fire_days = [5, 10, 15, 21, 30, 45, 60, 90]

# date_modes: 'alarm' uses ALARM_DATE as the reference, 'cont' uses CONT_DATE
date_modes = ['alarm', 'cont']

# Initialize list to collect results
results = []

url = "https://fire-recovery-backend-dev-113009620257.us-central1.run.app/fire-recovery/process/analyze_fire_severity"

# Loop through each fire, date mode, and post-fire day range
for fire_name in fire_names:
    bbox = create_bbox(fire_name, calfire_filtered_parks)

    for date_mode in date_modes:
        if date_mode == 'alarm':
            date_of_fire = get_fire_date(fire_name, calfire_filtered_parks)
        else:
            date_of_fire = get_cont_date(fire_name, calfire_filtered_parks)

        if date_of_fire is None:
            for post_fire_range in post_fire_days:
                results.append({
                    'fire_event_name': None,
                    'job_id': None,
                    'fire_name': fire_name,
                    'date_mode': date_mode,
                    'post_fire_days': post_fire_range,
                    'status': 'skipped_no_cont_date'
                })
            print(f"- {fire_name} ({date_mode}): skipped — no CONT_DATE")
            continue

        for post_fire_range in post_fire_days:
            query_data = create_query(fire_name, bbox.values[0], date_of_fire, post_fire_range, date_mode)
            
            try:
                response = requests.post(url, json=query_data)
                
                if response.status_code == 200 or response.status_code == 201:
                    response_data = response.json()
                    results.append({
                        'fire_event_name': response_data.get('fire_event_name'),
                        'job_id': response_data.get('job_id'),
                        'fire_name': fire_name,
                        'date_mode': date_mode,
                        'post_fire_days': post_fire_range,
                        'status': 'success'
                    })
                    print(f"✓ {fire_name} ({date_mode}, {post_fire_range} days): {response_data.get('job_id')}")
                else:
                    results.append({
                        'fire_event_name': None,
                        'job_id': None,
                        'fire_name': fire_name,
                        'date_mode': date_mode,
                        'post_fire_days': post_fire_range,
                        'status': f'failed_{response.status_code}'
                    })
                    print(f"✗ {fire_name} ({date_mode}, {post_fire_range} days): Failed with {response.status_code}")
                    
            except requests.exceptions.RequestException as e:
                results.append({
                    'fire_event_name': None,
                    'job_id': None,
                    'fire_name': fire_name,
                    'date_mode': date_mode,
                    'post_fire_days': post_fire_range,
                    'status': 'error'
                })
                print(f"✗ {fire_name} ({date_mode}, {post_fire_range} days): Connection error")

# Create dataframe and save to CSV
df_results = pd.DataFrame(results)
df_results.to_csv('fire_processing_jobs.csv', index=False)

print(f"\nProcessed {len(results)} requests. Results saved to fire_processing_jobs.csv")
display(df_results)

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ COFFEE POT (alarm, 5 days): 674b9f1e-0dd5-43b6-9717-998a5c8b10e9
✓ COFFEE POT (alarm, 10 days): 36dce962-a982-4e60-af53-eb061e0c6428
✓ COFFEE POT (alarm, 15 days): 7baa9569-e731-4d08-8869-7d2fcdbac731
✓ COFFEE POT (alarm, 21 days): 9b02f9a0-3373-4a8c-8743-1c58ab2f8b5c
✓ COFFEE POT (alarm, 30 days): eadd650b-94ba-4088-8b3f-9a3666ff4e1b
✓ COFFEE POT (alarm, 45 days): ddec762b-de4d-4670-a73d-12a53ac300da
✓ COFFEE POT (alarm, 60 days): 85002f05-85cf-47f7-8107-1c9173263016
✓ COFFEE POT (alarm, 90 days): 9c90c82e-1e02-443c-86c3-6fb44eedacf4
✓ COFFEE POT (cont, 5 days): f6c77f6a-c251-4b58-9ff7-bd0ab2791b61
✓ COFFEE POT (cont, 10 days): 2e73c62b-1cae-406f-931d-57a63dcd288e
✓ COFFEE POT (cont, 15 days): 8e1c2515-8071-415d-b9f6-541719c209b6
✓ COFFEE POT (cont, 21 days): 3eece749-1f67-4008-b030-80c3dedcf79b
✓ COFFEE POT (cont, 30 days): 45f60628-3113-485a-bc9d-df3783113ecd
✓ COFFEE POT (cont, 45 days): cbae0be9-978a-4f26-a4bf-3d069b19679e
✓ COFFEE POT (cont, 60 days): 5dd1f78f-713e-461f-96d2-9035045ae60a
✓ COFFEE POT (cont, 90 days): 18ab5f83-9f29-4fd3-ad00-f1cbcd52007b

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SENTINEL (alarm, 5 days): 6188fe33-d50d-41f5-9d08-2d446945bacd
✓ SENTINEL (alarm, 10 days): a573b98a-eaa7-421f-96cb-4b8096b04c6f
✓ SENTINEL (alarm, 15 days): 028587b6-754d-4215-9588-d1cf6706b1ac
✓ SENTINEL (alarm, 21 days): 9850a737-5679-43d6-bd2e-7803191c0951
✓ SENTINEL (alarm, 30 days): cf5b6bf5-34be-4204-af7b-6078f68af6e2
✓ SENTINEL (alarm, 45 days): b15b6e91-e846-4b3c-871a-9db35dfbf6ab
✓ SENTINEL (alarm, 60 days): bd468e18-c224-497e-a64e-d1a9da65e444
✓ SENTINEL (alarm, 90 days): cc96b483-f3d4-4695-a34c-9813cca9a1bd
✓ SENTINEL (cont, 5 days): c0055acf-fe07-4550-befc-b805ba553cff
✓ SENTINEL (cont, 10 days): a0f23e7b-271f-4f4d-ac36-9d3fede47fef
✓ SENTINEL (cont, 15 days): 303b11a7-cb15-42a3-9a0a-f257e84e2509
✓ SENTINEL (cont, 21 days): a78f6cb0-390f-4d0d-8eb5-c533e2ccc866
✓ SENTINEL (cont, 30 days): b143a40e-0392-4f10-9397-2336f776a582
✓ SENTINEL (cont, 45 days): 3755b83e-726a-41f2-bf55-1e8c3594734f
✓ SENTINEL (cont, 60 days): 5ddcc59e-0615-4c4a-ab9b-534f7d6d62bd
✓ SENTINEL (cont, 90 days): afae00fa-3ca5-447d-9be5-52d0120b41bc

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SIMPSON (alarm, 5 days): 90ec353b-b3ce-493f-a1c0-498cacdd1dbb
✓ SIMPSON (alarm, 10 days): 7e40b5d5-817e-4f3f-bef2-1ede4a04bdf5
✓ SIMPSON (alarm, 15 days): d8d83ea3-667e-4cc8-b749-38d173e3a5fb
✓ SIMPSON (alarm, 21 days): 8ca6adde-7059-487f-9624-ebe218bd510c
✓ SIMPSON (alarm, 30 days): 0f90ab6d-475a-4ee3-98c6-f0c25e0b1d5e
✓ SIMPSON (alarm, 45 days): df671949-619d-4317-b7e8-4e987ddbe369
✓ SIMPSON (alarm, 60 days): c21cc9ca-d3d6-474f-8bd8-4ba8db9db68a
✓ SIMPSON (alarm, 90 days): 06a55cac-746a-4506-bdf4-6e240cc8b2ea
✓ SIMPSON (cont, 5 days): f0c8bff8-3c46-4b73-a7c3-dac2b5aeeb5d
✓ SIMPSON (cont, 10 days): c724b371-f8b6-4214-a613-378406497b9d
✓ SIMPSON (cont, 15 days): 6f2921c2-3354-4d5c-9519-8169dccdb593
✓ SIMPSON (cont, 21 days): eedaaa5d-2f31-4666-924a-ef03aa1caed3
✓ SIMPSON (cont, 30 days): b53914a8-7bd2-4418-85c5-7b731e4d3d2e
✓ SIMPSON (cont, 45 days): 985e5507-380e-4e43-9fa5-2a49e437c4ae
✓ SIMPSON (cont, 60 days): a65f2174-52ef-443b-bbcf-82f387b6878a
✓ SIMPSON (cont, 90 days): c6a1e104-5bb6-48ef-823f-89e4e2f381a9

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ YORK (alarm, 5 days): 48331507-8b39-44e3-9241-680c5caef9e3
✓ YORK (alarm, 10 days): 69b0a4eb-c7fa-4821-ba98-1f7614779e0d
✓ YORK (alarm, 15 days): 81db95ad-90d0-4c38-90ba-3871edbcb023
✓ YORK (alarm, 21 days): 49e71da3-0e95-4db4-99b8-7eb1949ac8ce
✓ YORK (alarm, 30 days): 58c282e8-93db-474b-8243-79624eaba88d
✓ YORK (alarm, 45 days): a77e049a-342d-4ed7-8651-0ca29f01da6a
✓ YORK (alarm, 60 days): f036e36c-d909-4bac-a198-e4489c2660cb
✓ YORK (alarm, 90 days): 0d8771dd-f013-443c-ada2-7cac62fc82a5
✓ YORK (cont, 5 days): b62c4e9b-5b94-4114-95c6-d66526f1b0cb
✓ YORK (cont, 10 days): 2644bb19-bff8-49c2-8174-b40d8424fa00
✓ YORK (cont, 15 days): b4ef741d-e087-4b26-adf3-1de7a1229ca1
✓ YORK (cont, 21 days): 76a95241-ef11-4eae-8915-fa3628ffe336
✓ YORK (cont, 30 days): 38a539dc-0218-4da4-9c01-72a2ef9aa823
✓ YORK (cont, 45 days): 5096f06e-5521-45d5-863f-19e49eca60cb
✓ YORK (cont, 60 days): 9706f76f-ffa4-4264-8cbf-71d4849e474b
✓ YORK (cont, 90 days): 22bfddb7-b3b9-4756-bf24-3b1d744c6ce2

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ REDWOOD (alarm, 5 days): b3b3582e-9cd8-4740-a3c3-8f02b76205d0
✓ REDWOOD (alarm, 10 days): 69f41192-a3b4-426b-9b05-ab83aa97c118
✓ REDWOOD (alarm, 15 days): d3ccfaa4-0268-4143-82b2-4e39bbdba063
✓ REDWOOD (alarm, 21 days): 1c867177-7ada-4435-b239-73ddf18a63fa
✓ REDWOOD (alarm, 30 days): ec4aa066-7c2a-4637-852f-1b54650b31c2
✓ REDWOOD (alarm, 45 days): 26caeec3-b292-4248-b1ae-9f4901d0a3cb
✓ REDWOOD (alarm, 60 days): a9dcb7ed-888f-4669-bf16-e53c98589821
✓ REDWOOD (alarm, 90 days): e79123d5-132e-416d-a1d5-c405ae0264d4
✓ REDWOOD (cont, 5 days): 7f871865-a963-487c-9f53-1a5c43f29efb
✓ REDWOOD (cont, 10 days): 9a4b0beb-6093-4491-80f5-c6cbccef464b
✓ REDWOOD (cont, 15 days): 10ec52dd-6c26-4439-9c08-b02314ae9873
✓ REDWOOD (cont, 21 days): 42781ae8-b5cb-48d1-9251-d825a13c87e3
✓ REDWOOD (cont, 30 days): 266f2f2d-3f36-4f55-9e56-1b4d94666265
✓ REDWOOD (cont, 45 days): 62807f44-1869-4fca-809c-a12b187a87f1
✓ REDWOOD (cont, 60 days): f9945a9a-d499-48a1-add7-55c1e3e1da0a
✓ REDWOOD (cont, 90 days): b9235011-5af0-485b-a5a4-def3479c31e7

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ GEOLOGY (alarm, 5 days): 9e43a061-fc76-4e96-9e18-0bd595b31343
✓ GEOLOGY (alarm, 10 days): b93dbc6b-0bbe-4dd8-b2ed-2e0a57252ffe
✓ GEOLOGY (alarm, 15 days): 5c89f437-dc1d-42a7-9a05-660d8eb8475d
✓ GEOLOGY (alarm, 21 days): ba086e34-6a7f-4ccf-a585-3e7f72de2bad
✓ GEOLOGY (alarm, 30 days): 7c39efec-3665-4376-9a06-661b480785f3
✓ GEOLOGY (alarm, 45 days): 1aef7fee-83d4-467f-9b30-b6f99bab8fdb
✓ GEOLOGY (alarm, 60 days): 2cb9dfc2-0310-43e9-879f-852b385a6b7b
✓ GEOLOGY (alarm, 90 days): 029fdfdb-bd97-4c10-a413-f72aa853ade8
✓ GEOLOGY (cont, 5 days): b60316bc-b620-4146-9bbc-67a8a2abb177
✓ GEOLOGY (cont, 10 days): a902fadd-1423-46c9-ae08-697ae5e6688b
✓ GEOLOGY (cont, 15 days): efcce049-0f69-4284-838e-8557906a039f
✓ GEOLOGY (cont, 21 days): ec6d3fa2-7579-4165-b9a3-6177cc676183
✓ GEOLOGY (cont, 30 days): e65da15f-d9df-4234-9773-bf333a092c0e
✓ GEOLOGY (cont, 45 days): 247feb0f-2ca8-4ce1-b74d-ef06b8158b07
✓ GEOLOGY (cont, 60 days): 491cf58a-7204-4949-9b37-4afc3d80fe1d
✓ GEOLOGY (cont, 90 days): 980231f5-fe50-4ab6-a166-7f5f974002ee

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ VALLEY (alarm, 5 days): ee2cbb40-cb9c-4b14-a261-5fde259a707f
✓ VALLEY (alarm, 10 days): f9eb4fc5-22e6-465a-8dae-3a83f8dfc5ea
✓ VALLEY (alarm, 15 days): 600a6902-de7b-4f97-8509-cfb14d5ead87
✓ VALLEY (alarm, 21 days): 0613a585-1581-4918-9964-c10e3fc0751e
✓ VALLEY (alarm, 30 days): c3f6cb7f-0676-40f8-b31b-0fc3cf85dc69
✓ VALLEY (alarm, 45 days): 35f15ca5-f00b-4093-b5de-31af155b6e4c
✓ VALLEY (alarm, 60 days): 83a21f63-ac12-4691-bbf6-ad082a19be61
✓ VALLEY (alarm, 90 days): 1f725f69-0aea-4c4e-aeb9-15459c8176ef
✓ VALLEY (cont, 5 days): 337c9cb5-52fb-4c55-8938-630fb159ea07
✓ VALLEY (cont, 10 days): c5839219-652a-4ac5-b215-d163ba1b8b66
✓ VALLEY (cont, 15 days): 61c0c179-3500-4b8e-9b73-c1f4ccf873ed
✓ VALLEY (cont, 21 days): ac45d51e-8a46-4c39-ba3e-121a70cc8110
✓ VALLEY (cont, 30 days): b415f261-7cf8-40ca-8304-bfe7456bd2d8
✓ VALLEY (cont, 45 days): a55d0572-faa6-4581-838a-b54f72408fcd
✓ VALLEY (cont, 60 days): e1ede536-4340-4cf6-9bb6-513d44ed74c9
✓ VALLEY (cont, 90 days): b97067c7-4097-4fa7-9fa8-7a98ae80675f

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SYCAMORE (alarm, 5 days): 63a6c6e6-e625-46eb-9ea8-ba57963507d9
✓ SYCAMORE (alarm, 10 days): f5385f31-0082-4720-9b4f-1f69459c677f
✓ SYCAMORE (alarm, 15 days): d51e2e9a-7703-4ca4-b217-360bc26b42c0
✓ SYCAMORE (alarm, 21 days): b16e9850-3209-4ccf-9ba1-e5dd073c9e54
✓ SYCAMORE (alarm, 30 days): ac85f5a7-5446-4b82-9ac0-b45f8b42f205
✓ SYCAMORE (alarm, 45 days): 23f33cf3-92f3-4b98-827a-9ab6aae44a01
✓ SYCAMORE (alarm, 60 days): 7f671309-e9ad-4736-ac42-331e272bd8f5
✓ SYCAMORE (alarm, 90 days): c3fea720-13d5-4e1c-8fe5-50ed8359a3b1
✓ SYCAMORE (cont, 5 days): e2b47b64-4211-4842-b030-2094f8bf0392
✓ SYCAMORE (cont, 10 days): bfff33a1-4e66-444a-a5e1-01a40e44abee
✓ SYCAMORE (cont, 15 days): 8731a6df-af09-4723-8862-4046958da28f
✓ SYCAMORE (cont, 21 days): eafe367e-2e6f-4bf4-b227-955fed588a16
✓ SYCAMORE (cont, 30 days): e086770a-919e-4568-a0fc-d909f2a28fe2
✓ SYCAMORE (cont, 45 days): dcf0f142-356f-476c-9fe5-34d53495f601
✓ SYCAMORE (cont, 60 days): 3f515382-281f-49e4-b178-a020869b5347
✓ SYCAMORE (cont, 90 days): 8c9753cd-b3b0-4239-8154-a8730458343f

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SUMMIT (alarm, 5 days): 5da22535-2777-426d-b969-9c37068b4423
✓ SUMMIT (alarm, 10 days): 0a7b710c-e70a-4b05-b90e-ebf9bcca222b
✓ SUMMIT (alarm, 15 days): 813f47b1-cff5-44e4-8f0d-3055a4b0f89f
✓ SUMMIT (alarm, 21 days): 5ab0b291-d070-49ec-90df-16d6b18f3888
✓ SUMMIT (alarm, 30 days): 58879d2d-435b-4e30-9d3d-8696e7ff78f1
✓ SUMMIT (alarm, 45 days): 3e2b2bee-715a-4da0-b65f-441825b8ea30
✓ SUMMIT (alarm, 60 days): 52042bf4-af78-49c6-a79b-135880b47aaf
✓ SUMMIT (alarm, 90 days): 3b60231a-7e73-49b7-90cf-ca435edaddd7
✓ SUMMIT (cont, 5 days): d74aa962-0887-41d6-a698-649fdbcbea39
✓ SUMMIT (cont, 10 days): c56744b9-8065-4c55-928a-9a0b277819bc
✓ SUMMIT (cont, 15 days): 5950de15-e27c-4492-b3c4-cbeeb9b8cacb
✓ SUMMIT (cont, 21 days): c8f27b4f-b91d-45ef-8817-1b5db7f15c58
✓ SUMMIT (cont, 30 days): 6bbb791f-82d9-427e-b93c-e67cbd1d6244
✓ SUMMIT (cont, 45 days): 0f001e52-d1a8-4865-9641-dbe1eb42dcae
✓ SUMMIT (cont, 60 days): a005ca08-2d2b-41f5-ae6e-1ebe03c2b364
✓ SUMMIT (cont, 90 days): 56396899-0477-4a15-aa5e-413118417a9f

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ ELK TRAIL (alarm, 5 days): 4c456f13-8a2c-44f3-91ed-d11088d1bb0e
✓ ELK TRAIL (alarm, 10 days): eb7fe45a-722c-4db8-a8a8-37b3b6876745
✓ ELK TRAIL (alarm, 15 days): 9e75b34a-aba3-4526-b854-8a03391d3eb6
✓ ELK TRAIL (alarm, 21 days): 819b55e9-43d1-4f29-bdaf-8e27362dfb7b
✓ ELK TRAIL (alarm, 30 days): 95d1da63-f38c-4e80-ba09-a9fb3eb9474d
✓ ELK TRAIL (alarm, 45 days): 9b52c312-fb85-49c2-b19b-2d865f1d75d8
✓ ELK TRAIL (alarm, 60 days): 931bc26a-1e6b-4bca-a22d-e181b8dc5dcb
✓ ELK TRAIL (alarm, 90 days): 198cbb07-ee98-49b1-ab8a-aa683e9843f5
✓ ELK TRAIL (cont, 5 days): 7dedd85e-971b-4cc9-9e3d-b3f30a453e1d
✓ ELK TRAIL (cont, 10 days): 5dfc8a4e-a421-4bc1-bbfa-a7f707501c10
✓ ELK TRAIL (cont, 15 days): a2205680-8eff-42a7-abd5-696ca956c681
✓ ELK TRAIL (cont, 21 days): 6f10de61-f1bd-4b49-9fda-7048838b7b97
✓ ELK TRAIL (cont, 30 days): 1e0163ed-7523-4c1a-8b8a-a1c60de7d0e4
✓ ELK TRAIL (cont, 45 days): cf1b6709-ec2f-4ae7-b1cf-14a3aadb363a
✓ ELK TRAIL (cont, 60 days): 230225d2-b848-49d8-b5ac-c7442f13a912
✓ ELK TRAIL (cont, 90 days): 44731555-a1a3-45b0-aba5-eea7567ea09a

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ AVALANCHE (alarm, 5 days): 78cc07b7-041b-4e7a-a649-c3b117c765c8
✓ AVALANCHE (alarm, 10 days): c18f50b3-e435-4c24-9b4f-055472c23189
✓ AVALANCHE (alarm, 15 days): 88e8c2dd-fb90-40f7-bea4-0f20e1476fd3
✓ AVALANCHE (alarm, 21 days): 5b600ddc-1245-4a9b-a8ff-0020f34ffc50
✓ AVALANCHE (alarm, 30 days): 7ae03833-17ac-4c46-9cf4-d56d416eb40e
✓ AVALANCHE (alarm, 45 days): 8f2b9011-af5f-42fe-9a8f-4cb1bf7fc247
✓ AVALANCHE (alarm, 60 days): 36ec5950-8c5c-42de-a9dc-6e36272dce07
✓ AVALANCHE (alarm, 90 days): 6936bf27-53c5-4aa2-854a-cd320da10396
✓ AVALANCHE (cont, 5 days): 4d5726e7-e3c5-4399-bf8e-77a849ffd770
✓ AVALANCHE (cont, 10 days): 268e7dc0-47c9-4318-991d-a74f0f2d496c
✓ AVALANCHE (cont, 15 days): 3a0d8e33-643d-4a2c-a8ad-15b58a727645
✓ AVALANCHE (cont, 21 days): 8789a0c1-d3fd-4741-8f00-db1ebdbec283
✓ AVALANCHE (cont, 30 days): 909728f9-6993-4a9c-b47b-40063639b05f
✓ AVALANCHE (cont, 45 days): 4c5f388d-5347-4e76-8fea-0d508f3d4268
✓ AVALANCHE (cont, 60 days): 3b4c6b7c-e14f-4da4-bffc-d3e7388dca87
✓ AVALANCHE (cont, 90 days): aecc72b8-74d7-46a5-ad8d-2704ec942ed2

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ KNP Complex (alarm, 5 days): ece8c370-d841-40fc-bcf2-3e1091750a0c
✓ KNP Complex (alarm, 10 days): 842de757-35c1-44c3-a0a6-0936001246ca
✓ KNP Complex (alarm, 15 days): a5962f92-f09f-430c-8945-e4c05a65ce88
✓ KNP Complex (alarm, 21 days): bef2f899-046f-4d23-bc5c-afb405d4ce3b
✓ KNP Complex (alarm, 30 days): 377fefc0-159e-4e24-aab0-9420eed9e59b
✗ KNP Complex (alarm, 45 days): Failed with 504
✗ KNP Complex (alarm, 60 days): Failed with 504
✗ KNP Complex (alarm, 90 days): Failed with 504
✗ KNP Complex (cont, 5 days): Failed with 504
✗ KNP Complex (cont, 10 days): Failed with 504
✓ KNP Complex (cont, 15 days): 45a6ef55-0121-4252-9a5e-14b6b7340368
✓ KNP Complex (cont, 21 days): 3cadd4fc-6013-49b9-97eb-467e2334a8a7
✓ KNP Complex (cont, 30 days): 3916b161-5233-4e9f-a136-ebe7b3edebb4
✓ KNP Complex (cont, 45 days): db995c9d-aeea-461c-9087-b3c2ae8d8f61
✗ KNP Complex (cont, 60 days): Failed with 504
✗ KNP Complex (cont, 90 days): Failed with 504

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ MOJAVE (alarm, 5 days): 2a5b2428-726f-41fe-8914-bf25561bae29
✓ MOJAVE (alarm, 10 days): 0009a24d-0bfa-4ca9-914d-ca9a3d0bd262
✓ MOJAVE (alarm, 15 days): 7d7e682c-c45a-4cda-9188-ba693cc02d1d
✓ MOJAVE (alarm, 21 days): 76e422aa-bbb3-4ea5-b2f1-1d33e4dff1ea
✓ MOJAVE (alarm, 30 days): 5509be52-0bcb-4f38-8758-ccda443ebc22
✓ MOJAVE (alarm, 45 days): cfed1cc3-1f08-47f5-bb4b-cd3a475d758c
✓ MOJAVE (alarm, 60 days): 06575950-7da7-413b-8a23-ca8130b0c18e
✓ MOJAVE (alarm, 90 days): fb6a09f1-92b9-4ec1-b16f-790e30ebf62f
✓ MOJAVE (cont, 5 days): 46c12812-bce9-414c-a528-9fc1e6af5e25
✓ MOJAVE (cont, 10 days): 4a9db8b3-cb0a-41d3-a879-38c6f2a3bae1
✓ MOJAVE (cont, 15 days): 1dddcd9d-1a5d-461e-aada-33be1215b757
✓ MOJAVE (cont, 21 days): 77b53d2b-b611-4959-b93b-9b1b6b7fa213
✓ MOJAVE (cont, 30 days): 2f160650-6d2d-4125-8e01-2f845d40ae23
✓ MOJAVE (cont, 45 days): fa29c553-09bc-4473-b998-f6ed732093af
✓ MOJAVE (cont, 60 days): c140efd3-1f15-4052-9052-06401edb6668
✓ MOJAVE (cont, 90 days): 789f19a9-15ec-4d20-9ccb-68b953bc5525

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ POND (alarm, 5 days): 421ac574-e0e5-404c-82d7-d44ba8a2b6e6
✓ POND (alarm, 10 days): 7585d977-0e47-49e0-8b2c-00ec3c3656e7
✓ POND (alarm, 15 days): 7a1ed16c-4ce8-46be-96ea-fd81809aab85
✓ POND (alarm, 21 days): 9a7e5cd2-75ec-45a8-8241-bf6c82e3e526
✓ POND (alarm, 30 days): 0d83ccf5-a7ab-4f30-a4c4-397e89d24763
✓ POND (alarm, 45 days): a13abc8c-59d0-427b-ad90-098a72c5bf07
✓ POND (alarm, 60 days): 486b5714-f7ba-4a13-b006-2f9beeffad94
✓ POND (alarm, 90 days): 5446a955-d11a-431d-81ef-5e421860f53e
✓ POND (cont, 5 days): 898d582e-6795-47ba-ad81-ab5f20e87824
✓ POND (cont, 10 days): ce2c2eea-2cca-4f4e-93e2-9c46f755c7be
✓ POND (cont, 15 days): c7852129-b6f3-42a5-bc36-c366bda137b2
✓ POND (cont, 21 days): 8e1ff23e-b451-45ca-a803-5dd2eb294c09
✓ POND (cont, 30 days): 4dd2c7a5-6d4f-4175-80fa-b7a015438e1f
✓ POND (cont, 45 days): d2aea8eb-dbf8-4731-a103-b934ccfa5be2
✓ POND (cont, 60 days): afbb659b-8fda-489e-a77f-9a51e00058c5
✓ POND (cont, 90 days): 4ada9a9f-e152-40b2-8d63-5f99e45fa594

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ LOST (alarm, 5 days): 544628e1-8ee0-4bcc-b9e6-8b934a4e5ad1
✓ LOST (alarm, 10 days): 613003a5-ca8c-42a2-b436-d20028e80c4c
✓ LOST (alarm, 15 days): f6950e99-ab61-4a41-8179-6353cf12ed30
✓ LOST (alarm, 21 days): a8f4f749-417e-426f-8f79-344f988f39cf
✓ LOST (alarm, 30 days): d05a7c49-9a2c-4991-9e8f-c800222208a9
✓ LOST (alarm, 45 days): 3fe93c89-1a5b-4cc8-88fd-d25c8f82678d
✓ LOST (alarm, 60 days): ef5fc19c-3e57-4781-a8a4-6edee7f0931b
✓ LOST (alarm, 90 days): 0d920abc-8234-418f-9c35-e10b11f0bbda
✓ LOST (cont, 5 days): 834dcc3d-66ac-435e-88a7-66f5073d0279
✓ LOST (cont, 10 days): 0d3e1f45-5ff7-41ad-841c-01ad06c53c7f
✓ LOST (cont, 15 days): d588e5fc-6046-4384-a7eb-59d48b2e80af
✓ LOST (cont, 21 days): 73ca648f-aa38-4615-a1ad-37912f631d29
✓ LOST (cont, 30 days): c0566548-bb2a-40fc-b338-84c1491938db
✓ LOST (cont, 45 days): fb2ff590-0b58-49da-be9c-04f3cfcad2d4
✓ LOST (cont, 60 days): 2a61fa4e-f634-42ca-883a-d04c94d3cc28
✓ LOST (cont, 90 days): c31a1746-4b2f-4a20-a724-e2cf7777fbe5

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ HART (alarm, 5 days): 846511a0-7f42-4706-accd-0a9c96b170a5
✓ HART (alarm, 10 days): 62d8856d-682c-4034-83c6-2337f2c8d8b9
✓ HART (alarm, 15 days): 58d318b7-7541-4c2f-bec6-61858bfc38fe
✓ HART (alarm, 21 days): 1f4d5407-f6d8-49ff-8664-15330f28ca6e
✓ HART (alarm, 30 days): 4d129264-d72b-4fb0-b0c9-925275e9f539
✓ HART (alarm, 45 days): d58f60d1-b449-4d95-b132-d1d2f669dff9
✓ HART (alarm, 60 days): 0c79dadb-7563-4a6e-8170-208b78622d64
✓ HART (alarm, 90 days): 55fdaf95-63b5-4bc0-902d-d78523fe153b
✓ HART (cont, 5 days): 3578c988-38a4-45fd-bcc6-696b8357f5fb
✓ HART (cont, 10 days): 199eb32b-7996-43f0-950a-0e8ad0aab665
✓ HART (cont, 15 days): b5674a02-6f7e-4021-8db4-ec6ab75ea15c
✓ HART (cont, 21 days): 9c5ebdbc-96d9-42b1-a3e4-efd64116291e
✓ HART (cont, 30 days): 98f0fa1e-380f-4202-8154-01465b756395
✓ HART (cont, 45 days): f6bf3682-9884-4a1a-abc2-cc83ed4449f8
✓ HART (cont, 60 days): 0c809a8a-10de-47dd-930c-fc6d59fc7e4c
✓ HART (cont, 90 days): 3d7c5134-40e2-4ec5-8fb7-157cf07067e9

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ CASTLE (alarm, 5 days): 77793904-e8e0-45bd-8427-5bc028bbcf36
✓ CASTLE (alarm, 10 days): 97118dcb-b7cc-48a2-bb69-164e5a7c7532
✓ CASTLE (alarm, 15 days): e72266a4-3fb0-4a88-ba87-5493eb4c956c
✓ CASTLE (alarm, 21 days): 702e14ed-8189-49c4-85bf-68fdd4d9d536
✓ CASTLE (alarm, 30 days): c870f06c-2a17-4e0b-9612-fcc9ea1b71b2
✓ CASTLE (alarm, 45 days): 4139c4ba-4832-425d-b6f8-1fe52e0d05eb
✓ CASTLE (alarm, 60 days): 45f30080-5b05-4f9c-90e2-ae031bda7d5d
✓ CASTLE (alarm, 90 days): ddddf547-ae4c-4cad-bb78-7eabc0cfa042
✓ CASTLE (cont, 5 days): 0088101b-4fb2-4a98-a99d-a0d085075540
✓ CASTLE (cont, 10 days): 821ddb67-e027-4a0c-a096-d9deb555394b
✓ CASTLE (cont, 15 days): ba2b0e94-7ddb-42ce-b1d5-5f236d2c390a
✓ CASTLE (cont, 21 days): fbb6fe90-10ec-44ea-a444-f89222434514
✓ CASTLE (cont, 30 days): f6435391-b4c8-45bc-8f5e-5c851753f32f
✓ CASTLE (cont, 45 days): e3d4e7d1-dc33-4285-9579-e0090c476281
✓ CASTLE (cont, 60 days): 6c9315d2-5c9a-4ac1-a6a0-1d1a3bd728e4
✓ CASTLE (cont, 90 days): f431fb34-d894-40f8-a975-58b6a7c1bf20

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ DOME (alarm, 5 days): dd141d17-1179-4ffb-b2e3-ecb2f90063f3
✓ DOME (alarm, 10 days): 95287012-146d-4df9-b2f9-1cbcf56bf212
✓ DOME (alarm, 15 days): 6e7bbc9e-d5b2-4dbe-9d51-20bb900ab61b
✓ DOME (alarm, 21 days): 294cc7d2-db14-4a31-af95-ac83339a6c1e
✓ DOME (alarm, 30 days): 51c82a0a-2ae1-4d61-a820-9d79b3632c62
✓ DOME (alarm, 45 days): 12553891-3d09-49ac-8753-20c42827ecf7
✓ DOME (alarm, 60 days): 2999d245-809b-4c20-8cfa-7ba3ac69fe69
✓ DOME (alarm, 90 days): 68b98888-3b3e-4e48-a736-514952a148dd
✓ DOME (cont, 5 days): cfd1ffda-9d81-4aa6-aa8a-0fc85677e2bc
✓ DOME (cont, 10 days): df0c6939-b41c-444d-839a-0010f7acbcc2
✓ DOME (cont, 15 days): ab78aaa0-82e8-4c6e-9fb6-bbe5a0dbed50
✓ DOME (cont, 21 days): d7b83505-feb1-4d83-afe3-1cd3d726995c
✓ DOME (cont, 30 days): 9a74d63f-2ad3-4063-b005-bb1e5f4469cc
✓ DOME (cont, 45 days): a43ba94b-3a3b-4163-90e4-94aa58216064
✓ DOME (cont, 60 days): 9a816902-ae7d-46bc-90f1-a871a8b9ae94
✓ DOME (cont, 90 days): fffaee60-23c3-498e-a1a4-6f4658ca5beb

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ RATTLESNAKE (alarm, 5 days): 87e3b0de-607f-4370-ad2e-b13cb55ee863
✓ RATTLESNAKE (alarm, 10 days): f29d7d1b-068e-4eba-a569-e0ccdce924b2
✓ RATTLESNAKE (alarm, 15 days): f0f1edb5-1cd7-45a9-8190-90504947dc57
✓ RATTLESNAKE (alarm, 21 days): d95bc2e2-00b8-41c0-8284-5fdfeb5a806b
✓ RATTLESNAKE (alarm, 30 days): d80b0524-360b-45db-b977-29007c5a5d35
✓ RATTLESNAKE (alarm, 45 days): 6de434fe-27c8-4dff-9831-4266116ace82
✓ RATTLESNAKE (alarm, 60 days): 958289c5-cd1e-436c-9a9f-e97b5ee05085
✓ RATTLESNAKE (alarm, 90 days): 1436ca9b-c810-4a1a-9dd4-2342c73e08a7
✓ RATTLESNAKE (cont, 5 days): 7c24245a-3985-4052-a34f-b0622c77e210
✓ RATTLESNAKE (cont, 10 days): 72c9c809-afcf-4865-824c-f2b00737df5c
✓ RATTLESNAKE (cont, 15 days): bff30cb2-359f-4bf4-bae0-8d8edce59a07
✓ RATTLESNAKE (cont, 21 days): 58aad421-998d-4161-8c3d-2f3e0474fce7
✓ RATTLESNAKE (cont, 30 days): 46a4dd6d-f1c7-4f85-ba68-882be099ad33
✓ RATTLESNAKE (cont, 45 days): 684dcc15-1774-4572-8dd8-c7e22536bf19
✓ RATTLESNAKE (cont, 60 days): d7401683-6d5e-4214-ab63-a57fd4a7bde2
✓ RATTLESNAKE (cont, 90 days): e0a6b626-8304-487a-8e8f-e55fb134ea20

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SCORPION (alarm, 5 days): cc15f7b0-4fa6-47d0-825e-09daa3877914
✓ SCORPION (alarm, 10 days): 4b735c0e-8354-4ab3-9a2c-bb21b8fd0a2d
✓ SCORPION (alarm, 15 days): 075f7cea-4a26-41eb-8cc4-916998b8a3e8
✓ SCORPION (alarm, 21 days): f730da53-506b-40be-b984-8a9aa2b1fc27
✓ SCORPION (alarm, 30 days): 9a3c4741-3764-4dbc-b27f-73f229ad06cf
✓ SCORPION (alarm, 45 days): b56bb966-b8c2-49e5-8037-7930ff4be90e
✓ SCORPION (alarm, 60 days): 7ee79d99-610a-4a1b-8fd0-d485ec56ba3d
✓ SCORPION (alarm, 90 days): 04da3c87-4fce-4c0a-8c40-42740551e739
✓ SCORPION (cont, 5 days): 527d17a4-5357-4bb1-9a08-9b72ff32883c
✓ SCORPION (cont, 10 days): 326f8f0f-0a13-4109-86c1-832297959f9b
✓ SCORPION (cont, 15 days): 793a25f1-ab98-4014-9c0d-d8f7a043a3ab
✓ SCORPION (cont, 21 days): c388f50d-d21e-4a8b-9b71-be38cc124986
✓ SCORPION (cont, 30 days): b597f8bb-16b7-4b3b-b736-01fd9cb7dde9
✓ SCORPION (cont, 45 days): 8a6f2226-7b6a-4320-b4bd-95acf667601c
✓ SCORPION (cont, 60 days): 300cc236-baa8-4363-930b-b58274a8d754
✓ SCORPION (cont, 90 days): 42de0cec-f6d1-40b5-9875-b4531c6b662c

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ MORAINE (alarm, 5 days): c54d72a7-2ad5-4a91-8e4c-d5b3a5b495c3
✓ MORAINE (alarm, 10 days): 889bd838-4d84-4f9c-8897-969d401b1d88
✓ MORAINE (alarm, 15 days): 9b865b53-ed88-47ec-b44d-3bf2db8a0419
✓ MORAINE (alarm, 21 days): 044b42de-1f65-4777-8971-0ab6de1b4f24
✓ MORAINE (alarm, 30 days): dbf1b8ac-923d-4231-89ed-b3a793fb80dc
✓ MORAINE (alarm, 45 days): 12bb611e-bb4e-4384-a3f8-fb82985a0f76
✓ MORAINE (alarm, 60 days): f442b919-1fac-4a59-b690-95c04071efdf
✓ MORAINE (alarm, 90 days): 93fb057b-5912-473d-b00b-847e3764f76c
✓ MORAINE (cont, 5 days): 9d76cfd5-c33f-4507-a698-b8ac1a161f8b
✓ MORAINE (cont, 10 days): d7018254-e3cd-434a-9233-04e21a40dcc1
✓ MORAINE (cont, 15 days): 0bd99691-94d2-45da-bf5b-4067db14be59
✓ MORAINE (cont, 21 days): cac7d925-03e9-4522-a4a5-79269f540e99
✓ MORAINE (cont, 30 days): ae1b1497-f3c9-4a22-921e-47419a4754f0
✓ MORAINE (cont, 45 days): ac3dea77-d1ce-4dea-8259-cbe5b479b100
✓ MORAINE (cont, 60 days): ec434f83-e1a9-42d3-83d1-9785efcb9f09
✓ MORAINE (cont, 90 days): 3e0d7867-41da-40c1-9b94-434d1ce75c47

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ IVANPAH (alarm, 5 days): 2c75c719-5cc8-48a3-a931-bc7ffec18f53
✓ IVANPAH (alarm, 10 days): ac661e20-0b0d-4e9d-8fe7-656f6671e2c2
✓ IVANPAH (alarm, 15 days): 32d1714d-a744-4aa5-ae36-e32c82a404b5
✓ IVANPAH (alarm, 21 days): e3f98907-13c6-4e1d-afa0-1f1e9c9bbeac
✓ IVANPAH (alarm, 30 days): 73bc078d-df9a-4ed2-887e-b79dd2153370
✓ IVANPAH (alarm, 45 days): f703e938-3941-421e-bc1b-827f80c622a9
✓ IVANPAH (alarm, 60 days): cd768a51-b65c-4547-9956-75f937861638
✓ IVANPAH (alarm, 90 days): f7f137f8-8a67-4029-8b06-3668fc39d52f
✓ IVANPAH (cont, 5 days): e7a6fe8f-f0b4-4cf6-83e1-bdd748219a3a
✓ IVANPAH (cont, 10 days): fb842366-47fc-4985-8694-44d352c055f1
✓ IVANPAH (cont, 15 days): 61af887c-ff65-4289-96e8-dd107e8f0efa
✓ IVANPAH (cont, 21 days): b585a29c-b90c-4d7b-8649-4f56cd2532e0
✓ IVANPAH (cont, 30 days): 4d3a7584-86d7-480f-b83e-c58c3acc1023
✓ IVANPAH (cont, 45 days): 2d8656f8-2f83-4079-862a-2696fc4092f5
✓ IVANPAH (cont, 60 days): e87fd57c-33ec-4fde-b243-1278e4ea0ce2
✓ IVANPAH (cont, 90 days): 4c1f77ad-5d8d-4ec1-a040-d6051467942a

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ BULL (alarm, 5 days): 4d610b9e-435e-47fe-a5c5-f11276d99bf0
✓ BULL (alarm, 10 days): 840e2886-888f-4426-9368-45216d7517ba
✓ BULL (alarm, 15 days): 60213777-a989-45b1-90b7-97181ef3f531
✓ BULL (alarm, 21 days): d6fcf9c7-9a8a-4b95-8e10-18a98d2d4791
✓ BULL (alarm, 30 days): 93ed3f40-aa8a-4ecf-a4ab-c117a06b3fc6
✓ BULL (alarm, 45 days): 5fbd30dc-337b-4c20-b5b6-8ddf18496cb1
✓ BULL (alarm, 60 days): 65dc013a-5da5-485c-a5f4-4295febdfdcb
✓ BULL (alarm, 90 days): 9f973557-1183-4d7d-8314-d7b19e34fad4
✓ BULL (cont, 5 days): 115238e8-90bc-4acc-904c-3bbcd3deecf2
✓ BULL (cont, 10 days): f1419eed-3832-47d9-93a2-98115ec6fc76
✓ BULL (cont, 15 days): e655a88a-a830-4876-be17-b1a6aacaa81a
✓ BULL (cont, 21 days): 5ddb7af3-83cf-414d-b1ef-faa52f43020e
✓ BULL (cont, 30 days): f30195d4-8349-481a-8a08-130a2727a6be
✓ BULL (cont, 45 days): a93d1748-65a9-4125-8ad8-636bfe0a3ae7
✓ BULL (cont, 60 days): 4c208714-0027-4565-9d3c-c7498f685584
✓ BULL (cont, 90 days): a7e02e99-5bfd-4a1b-b254-12582e4952af

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ WENDY (alarm, 5 days): 4aa61154-d30f-47f0-a686-caecac9c027f
✓ WENDY (alarm, 10 days): f5e4ed07-b1a4-4cd3-b1e8-54a1e7b288f2
✓ WENDY (alarm, 15 days): 66856b50-fd5c-4d8a-a9b3-32fd74845d9a
✓ WENDY (alarm, 21 days): a97bc9f3-da21-4af5-a936-d2d69a9404a7
✓ WENDY (alarm, 30 days): c46cda3f-05f1-40a9-8f8e-e9d06f86884a
✓ WENDY (alarm, 45 days): 63076e81-6fe7-43d5-ac14-2e3753618924
✓ WENDY (alarm, 60 days): da7635d4-2c7b-4f64-b70f-39944fb7a223
✓ WENDY (alarm, 90 days): 88825ce2-2455-4b17-8c9d-2e51b29c84cf
✓ WENDY (cont, 5 days): fba3c8c7-6297-434d-9d96-f078e9b5e201
✓ WENDY (cont, 10 days): 523c4872-5852-46ce-be56-15d5c8462f18
✓ WENDY (cont, 15 days): e8f63deb-8f28-4427-811e-c572e8e9557d
✓ WENDY (cont, 21 days): 707d4d43-9830-49e4-b03a-3f2f66169270
✓ WENDY (cont, 30 days): e0e5e578-f6f2-4ae9-94b9-eb3028c13d17
✓ WENDY (cont, 45 days): 0f305566-14ee-49fd-81fb-bd5b8793081b
✓ WENDY (cont, 60 days): 97feae7d-f7be-456b-b00c-bdb78de19473
✓ WENDY (cont, 90 days): 1fd62b34-4fdd-4e80-89be-d37b13a92e16

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ STAR (alarm, 5 days): 2f126cb0-bca4-4ff5-a47c-48062329ddbd
✓ STAR (alarm, 10 days): 34460c34-2c76-4080-ad3e-e4ce653564b6
✓ STAR (alarm, 15 days): 8b82360c-0871-4b5b-8018-b9e545c22702
✓ STAR (alarm, 21 days): 6d30e658-18b7-451d-8d1e-02dcc201909b
✓ STAR (alarm, 30 days): 959c1cd7-3c96-4f6c-8724-4a37cda048e8
✓ STAR (alarm, 45 days): 306f7756-ec78-40a3-99dd-5cc87e8b351d
✓ STAR (alarm, 60 days): f5ac2079-2aa4-45ed-b5d3-eb7d34b0f336
✓ STAR (alarm, 90 days): aebbeff8-3f1f-4caa-b2b0-0cfbfc4d8ac1
✓ STAR (cont, 5 days): 1f3b76fa-050c-436a-a666-ffdafcb2c255
✓ STAR (cont, 10 days): bfc05b34-b034-4a83-8aa7-73eb6aecee35
✓ STAR (cont, 15 days): a56ef5c0-dab4-461e-8cfd-fff555e6a401
✓ STAR (cont, 21 days): f16c0669-119d-44c4-ab74-b28ab523a9ed
✓ STAR (cont, 30 days): 9838dac9-2f84-41fc-96fd-a4eb588e9881
✓ STAR (cont, 45 days): c4ab5f3d-76f5-43c1-8a9c-93fad3716e10
✓ STAR (cont, 60 days): f6398b13-fdc2-4280-8632-f0d854dfaa68
✓ STAR (cont, 90 days): 88bbcb4b-ac14-44f9-ae5f-d6101bc890fb

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ EDEN (alarm, 5 days): 4e4bcafa-d759-4c37-b84e-176b5416acc6
✓ EDEN (alarm, 10 days): 9b8819bb-caca-4b8a-80e1-6cdf7bf40203
✓ EDEN (alarm, 15 days): 5eae959c-bab6-49c1-9752-e95248f0386b
✓ EDEN (alarm, 21 days): b3420c96-8596-45d3-944a-632a76216af4
✓ EDEN (alarm, 30 days): 0f00d158-863a-4856-94a3-5bd0c216e1ee
✓ EDEN (alarm, 45 days): 5df1ac46-64ae-4735-81c2-2401a9314266
✓ EDEN (alarm, 60 days): 6f9acd6b-5da6-4ca4-a6e7-718b63f179cf
✓ EDEN (alarm, 90 days): 4b005a46-6365-413c-8a5d-ee8cd1ca355c
✓ EDEN (cont, 5 days): db2738b2-e191-4c31-b693-748e6e945fd2
✓ EDEN (cont, 10 days): d7b87d3c-63f0-42eb-b15e-8624c8cf9d78
✓ EDEN (cont, 15 days): cdb0dd85-f4ed-401f-a251-c9199c0671fc
✓ EDEN (cont, 21 days): d3289d14-20f4-4bec-8a99-3f50090c1e02
✓ EDEN (cont, 30 days): fbe053e6-c8b9-408c-a216-bdb468b3d990
✓ EDEN (cont, 45 days): 7546ae54-9992-4699-80ea-0aaf2b9f700d
✓ EDEN (cont, 60 days): d68e6053-4cd0-45fa-b863-2caff094d205
✓ EDEN (cont, 90 days): 88130550-f76a-451b-96fe-f942e779c561

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SANTA CRUZ (alarm, 5 days): 0ed134f9-bee3-4745-9a7d-02b0197cab66
✓ SANTA CRUZ (alarm, 10 days): b6c4f3f4-104e-4c1c-ac87-3eb95345f2eb
✓ SANTA CRUZ (alarm, 15 days): 35d8755d-58c4-4b3a-a3ea-5bd67b7c23c5
✓ SANTA CRUZ (alarm, 21 days): cf0ac56b-ebae-4f26-903f-57ce56565825
✓ SANTA CRUZ (alarm, 30 days): dce71346-555a-4a9f-bec5-6119e2202063
✓ SANTA CRUZ (alarm, 45 days): a4f703d5-5dc0-4335-8dc7-eb21db97284a
✓ SANTA CRUZ (alarm, 60 days): 6c507c44-2ce1-4a53-9ec7-0ca235086258
✓ SANTA CRUZ (alarm, 90 days): 4feab670-5d5c-4035-bb62-20e5231d54fb
✓ SANTA CRUZ (cont, 5 days): 6beb2bef-4d06-4f0c-8b19-611e857d65e1
✓ SANTA CRUZ (cont, 10 days): 0925a44a-f8cd-46ad-9b1b-87b65d5d70d5
✓ SANTA CRUZ (cont, 15 days): 821732f8-9e06-42bd-bbe1-4dcf9c9888f5
✓ SANTA CRUZ (cont, 21 days): 9a98c7e9-a035-4000-beff-9416f1a5a2c7
✓ SANTA CRUZ (cont, 30 days): 7874f2d8-7466-4dc4-be4a-92f8f857348c
✓ SANTA CRUZ (cont, 45 days): eb82c516-22d3-4326-a442-eae3fdea15d0
✓ SANTA CRUZ (cont, 60 days): 50e4d455-d39f-48d5-9faa-6ec7d35df875
✓ SANTA CRUZ (cont, 90 days): 743e28f1-4e53-49df-8d2f-50e890a48738

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ NORTH BUBBS (alarm, 5 days): af5172c3-5a9f-4d94-b0b1-d0f5f053fdd2
✓ NORTH BUBBS (alarm, 10 days): f9bb2e23-4cd8-4e23-bfab-9b0af4238c57
✓ NORTH BUBBS (alarm, 15 days): c51002e2-df71-4a03-bda6-4657b2c2fe8b
✓ NORTH BUBBS (alarm, 21 days): 1f98b7c6-73d3-4f5e-87e1-891c131fe49e
✓ NORTH BUBBS (alarm, 30 days): b364e3cb-52aa-4e53-9ad5-dc7ef6fbb446
✓ NORTH BUBBS (alarm, 45 days): a91680ce-7f8a-4b01-a8ef-6e7fd794c210
✓ NORTH BUBBS (alarm, 60 days): 1796c344-90ba-4d8b-99fb-9520b302afea
✓ NORTH BUBBS (alarm, 90 days): b6f8b4e6-9762-4c99-92d2-171183c01ef2
✓ NORTH BUBBS (cont, 5 days): 721ef2bc-7dfd-4664-9623-66ed865f571c
✓ NORTH BUBBS (cont, 10 days): 5a8c6386-7b04-41b7-a19e-ede464163dab
✓ NORTH BUBBS (cont, 15 days): 2e2d036d-b652-4a05-98df-cec6e5108954
✓ NORTH BUBBS (cont, 21 days): 2fc2a025-d257-4469-8270-9bce48b59fc0
✓ NORTH BUBBS (cont, 30 days): e0dc56ad-5457-4f13-909b-8d9d2f73ac56
✓ NORTH BUBBS (cont, 45 days): 3d4555b7-7040-4d4a-8fa4-0b487bb4435f
✓ NORTH BUBBS (cont, 60 days): 071d935a-854c-4602-a880-7a9c4ca8872a
✓ NORTH BUBBS (cont, 90 days): 14291011-5418-4d24-9bcc-5ed143da0e4b

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ DENNISON (alarm, 5 days): 8d21d9dd-02e9-44ba-8253-6e81030c596b
✓ DENNISON (alarm, 10 days): 33904149-da89-49dc-8033-379dc4f4b2e5
✓ DENNISON (alarm, 15 days): da8d2522-0e38-4fa0-842d-bc121e1f6825
✓ DENNISON (alarm, 21 days): f304879e-a9fc-41f4-a1d2-fb3e1d53d01f
✓ DENNISON (alarm, 30 days): bf84d1ae-16b5-4a2c-90cd-623c69602e66
✓ DENNISON (alarm, 45 days): 4fc15652-90e0-4a71-8cbe-b2d0aefe672e
✓ DENNISON (alarm, 60 days): cb8ab19b-c5c6-49b7-b8c9-11e41cba07fd
✓ DENNISON (alarm, 90 days): d5bff6f6-a561-41e9-b2fc-e26a74c93249
✓ DENNISON (cont, 5 days): f4648034-af71-4a6a-97ec-3c8ec003cd7e
✓ DENNISON (cont, 10 days): 6a1bf706-1920-46c9-8d0e-4bfeb79ae59f
✓ DENNISON (cont, 15 days): e7dd9bbc-14c1-48cf-b6e9-34f6abfba3c9
✓ DENNISON (cont, 21 days): a2a8f300-2720-4f68-a7eb-6b69c6fdc49e
✓ DENNISON (cont, 30 days): 45dd79eb-c65d-4052-a167-2280401d7a08
✓ DENNISON (cont, 45 days): 7f19fee1-4fb2-4576-94eb-d06e7dcc55af
✓ DENNISON (cont, 60 days): a03af2f2-08aa-4943-920b-081e2f08ce36
✓ DENNISON (cont, 90 days): 86db3d0d-242f-4b39-8613-0ae99d0c181a

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ HORSE CREEK (alarm, 5 days): 1c3ba944-1b75-4423-966d-ad2b7ca4a7cd
✓ HORSE CREEK (alarm, 10 days): 5a480462-52e8-437e-a983-48d49e1f9fd3
✓ HORSE CREEK (alarm, 15 days): 5ab05003-92d0-4002-8d1d-461a5bc53746
✓ HORSE CREEK (alarm, 21 days): 4b9fa103-c71e-4e17-b824-f7240fcde343
✓ HORSE CREEK (alarm, 30 days): 0b996150-24bf-4a85-9c92-a6ba86fd4717
✓ HORSE CREEK (alarm, 45 days): 4690830e-8bc8-48b4-94b4-9de47d637a35
✓ HORSE CREEK (alarm, 60 days): 4649d701-3d42-4a86-94f0-d13e375b2031
✓ HORSE CREEK (alarm, 90 days): 2de6782b-3f8c-4cf3-aacb-108a75ae3c95
✓ HORSE CREEK (cont, 5 days): 16ee687d-918d-4345-b8cc-d5b4d78fd39b
✓ HORSE CREEK (cont, 10 days): 7dce5be6-f7c6-40f8-bed8-d97e5db530b4
✓ HORSE CREEK (cont, 15 days): d9efdb93-27a6-4a1a-bfd7-b6d358473b53
✓ HORSE CREEK (cont, 21 days): aed516d6-b6fe-4f66-8f20-580699d0c2b1
✓ HORSE CREEK (cont, 30 days): 512836fa-ca74-4a3c-8040-9c5d21b10e3f
✓ HORSE CREEK (cont, 45 days): 82d73959-22eb-4432-a756-0ca8f88ed7d9
✓ HORSE CREEK (cont, 60 days): 6f64d7c1-c9b8-43f9-b61a-97be9b361986
✓ HORSE CREEK (cont, 90 days): 9620f330-3435-4688-aebf-909d3ef3d641

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ SERRA (alarm, 5 days): 9311c738-5297-4a79-8a04-7c20cfcb0012
✓ SERRA (alarm, 10 days): bd51fa41-5154-4504-b056-f59a309b68e9
✓ SERRA (alarm, 15 days): 046b0bfc-c965-4990-b267-8eb72e54bad3
✓ SERRA (alarm, 21 days): 84e6e733-8a0c-4792-a7a1-4de48c664c37
✓ SERRA (alarm, 30 days): 6af61d00-a4e4-4fe7-b745-769a8099d2a7
✓ SERRA (alarm, 45 days): 9a17d8e0-a431-41ec-af6f-3e8325b83583
✓ SERRA (alarm, 60 days): 8d273540-9d57-4743-b3f3-b3b0aab8ffda
✓ SERRA (alarm, 90 days): a0c7b6b1-e5f1-4eec-976b-b3539695e3ce
✓ SERRA (cont, 5 days): 007a6ac7-ef08-4523-a348-49ee83a1895d
✓ SERRA (cont, 10 days): 96b1e936-2abe-4f03-909d-cc9ed06e9630
✓ SERRA (cont, 15 days): 7f1b7049-c5d8-4af9-94f3-1eefbee8904c
✓ SERRA (cont, 21 days): 3825198d-dd9b-4ff3-a723-de920eea5be4
✓ SERRA (cont, 30 days): 5f330bdc-b7d3-4288-a7e9-eb6fc2ba29b7
✓ SERRA (cont, 45 days): e874311c-86a1-4286-bc8c-b48b865ad7f7
✓ SERRA (cont, 60 days): 6fe44221-6349-4a99-b967-b7579c512438
✓ SERRA (cont, 90 days): 3ca2d8f1-7a69-47c1-8ea9-9390a3ea65fe

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ THARPS (alarm, 5 days): f8504887-5a16-45e2-a8b5-0c6e936885c4
✓ THARPS (alarm, 10 days): 6f764fd6-0a71-4dd9-bfe7-0dd659c3c2f2
✓ THARPS (alarm, 15 days): 81359a8e-3a73-452f-b02e-7b9e173a7111
✓ THARPS (alarm, 21 days): 16dbd057-f947-4c34-8063-be1e1de2ac76
✓ THARPS (alarm, 30 days): 33029bb6-7517-4151-b028-ccd0317948f5
✓ THARPS (alarm, 45 days): 0a041510-4653-4608-90a1-217d81e886f1
✓ THARPS (alarm, 60 days): 312bb14d-cb48-4677-8736-2a51c385f39b
✓ THARPS (alarm, 90 days): aa360e06-df50-494a-9218-32b0adf799a0
✓ THARPS (cont, 5 days): 6aeb0afb-7e39-45b6-9421-576a652dfb6a
✓ THARPS (cont, 10 days): d2b85468-6185-43a0-9145-ea38325e524e
✓ THARPS (cont, 15 days): 3cb43e00-9896-4e7f-9041-7cfde143316a
✓ THARPS (cont, 21 days): 665005f0-64fd-4718-b00a-12856f6993dc
✓ THARPS (cont, 30 days): 3a2a213b-737d-4c9f-9b0f-df9b3e1f7599
✓ THARPS (cont, 45 days): 506739fe-680c-4185-9c7a-4870dfc8ff05
✓ THARPS (cont, 60 days): e3fae076-cf4f-445e-a7b8-a6587df56616
✓ THARPS (cont, 90 days): 68ac198a-ea9d-44a7-849f-06c7ba532b56

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ KNOLLS (alarm, 5 days): c487de59-1ee4-43ec-8e64-fb93310fa48c
✓ KNOLLS (alarm, 10 days): 59f6c4c9-a819-4cdf-ab7a-2d2fd9dd8310
✓ KNOLLS (alarm, 15 days): 8daefcd8-ac6c-4594-a379-f03fbb0b44e7
✓ KNOLLS (alarm, 21 days): 1573c04a-6f04-4985-8114-a18589bb98cc
✓ KNOLLS (alarm, 30 days): 246356bb-b477-45e0-84d6-5cb7afc0124b
✓ KNOLLS (alarm, 45 days): 4b5641f8-9bec-4d02-b453-2afcd46e8236
✓ KNOLLS (alarm, 60 days): 8f8f0258-b4ae-4702-98c9-94ce675dcf73
✓ KNOLLS (alarm, 90 days): e0570b49-8fad-4a40-8ad3-a3cc4fa924bc
✓ KNOLLS (cont, 5 days): a5e96b57-7b8a-42c7-b389-a965ac412670
✓ KNOLLS (cont, 10 days): 55c6a762-b34e-48d6-8ab0-c4e8ea669cfe
✓ KNOLLS (cont, 15 days): b1d8f1a5-488e-43e7-bd5d-9a8a95c3a366
✓ KNOLLS (cont, 21 days): 50a23de9-a4aa-49c5-ac56-d02a9af1c72f
✓ KNOLLS (cont, 30 days): 5066d281-f5dd-4013-8436-e7e73a84d954
✓ KNOLLS (cont, 45 days): 18b0a593-d147-42b3-a192-2ee8b590bf58
✓ KNOLLS (cont, 60 days): 7bdc0fb4-fab6-468a-8c21-53e561bb994d
✓ KNOLLS (cont, 90 days): 17c1e8c9-4565-4eec-b192-8f281a339bc7

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ CORNELL (alarm, 5 days): d71ae3c5-8b13-433a-b00f-507977582275
✓ CORNELL (alarm, 10 days): 323a56ae-af0c-4212-b786-93022f09564e
✓ CORNELL (alarm, 15 days): f6d677ee-fc8a-48d4-8e82-7b0b581867ad
✓ CORNELL (alarm, 21 days): 4bf9b177-d73e-4f8a-a45a-4aca1800dbd1
✓ CORNELL (alarm, 30 days): 30e63518-2546-4a68-ab2a-87116a92ab72
✓ CORNELL (alarm, 45 days): 2f7b16ec-fa69-4e62-9e66-b66cbcdd3bae
✓ CORNELL (alarm, 60 days): e114ba8a-73ca-4acf-b427-31f0dc4fcb61
✓ CORNELL (alarm, 90 days): 632c1c19-1b10-44f0-9e0a-3d3b80914898
✓ CORNELL (cont, 5 days): 009ffaba-3a5d-43c7-b0ae-b988dea744f5
✓ CORNELL (cont, 10 days): 6540755d-d4d5-4378-a076-49da5b149b53
✓ CORNELL (cont, 15 days): 7c8dc31e-79cb-4a57-a922-ee79c40f882b
✓ CORNELL (cont, 21 days): 45777277-12ae-490e-add3-e2a6c07f5ae5
✓ CORNELL (cont, 30 days): ab0cc89e-5332-49a5-9442-667e1fa43dd7
✓ CORNELL (cont, 45 days): f8c6b443-1964-44b6-94c4-18268a7cf26e
✓ CORNELL (cont, 60 days): 79a54f62-952b-4b0c-8633-eab780a0c45f
✓ CORNELL (cont, 90 days): 29e73307-599a-4e1d-9b73-f0bb0c20666f

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ NORTH GUARD (alarm, 5 days): a362bca6-d798-4321-8a1d-bf0a02d83b40
✓ NORTH GUARD (alarm, 10 days): 6e1a6c1a-2950-4bb5-9847-a3b4a8aaa9d6
✓ NORTH GUARD (alarm, 15 days): c5b96f6e-aada-4ec0-ae88-ad2ee36d94fb
✓ NORTH GUARD (alarm, 21 days): 91f78ac7-0076-44a1-8692-928b778e4a83
✓ NORTH GUARD (alarm, 30 days): a6c5272d-77eb-4412-adac-520386f7b51c
✓ NORTH GUARD (alarm, 45 days): a97af93c-1f83-447d-9e65-ac9a38e93b74
✓ NORTH GUARD (alarm, 60 days): 9dd198df-0364-4933-86fc-e0ba3b32da7b
✓ NORTH GUARD (alarm, 90 days): b095ea78-a932-4c8c-9328-5dbe160d4621
✓ NORTH GUARD (cont, 5 days): e9416f0a-7c8a-4b28-9c54-28f13f27df2b
✓ NORTH GUARD (cont, 10 days): 0bea5310-2696-4286-8a9c-f1c116043b17
✓ NORTH GUARD (cont, 15 days): bdf85205-11b7-4675-8a62-92faad799020
✓ NORTH GUARD (cont, 21 days): b9f641bf-0342-46e6-a97f-47e7b8f0bc69
✓ NORTH GUARD (cont, 30 days): 7411840a-3fee-4c9c-b0f4-8fa4ee7fa02a
✓ NORTH GUARD (cont, 45 days): 477dcdfa-bd73-401c-973f-6abf476d31f8
✓ NORTH GUARD (cont, 60 days): 39bb0a40-0ffb-4c3b-a814-e80afbe26807
✓ NORTH GUARD (cont, 90 days): 2111d1ed-0021-4f03-accc-2e568f8cb3c2

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ GRANITE (alarm, 5 days): 9be90028-7730-4bc9-b69e-aa3c71812d20
✓ GRANITE (alarm, 10 days): f8aeed5c-e24a-4a7c-9e42-9d6154ce2eae
✓ GRANITE (alarm, 15 days): ad5bbcc2-1faf-4270-acc8-b0f4788de154
✓ GRANITE (alarm, 21 days): e2df5ab0-6075-41b9-90e3-37a78a3cbcdb
✓ GRANITE (alarm, 30 days): 7eb39bf0-3c7f-4482-b122-62e0b85640b2
✓ GRANITE (alarm, 45 days): bc1284ab-11cd-40a7-9256-4366c8044f23
✓ GRANITE (alarm, 60 days): e0e9cbd9-7948-4757-a169-51cb56a2dbf3
✓ GRANITE (alarm, 90 days): e1f0df21-1aa8-402c-9957-e22e512a0654
✓ GRANITE (cont, 5 days): 77ab83c8-670b-45e7-9697-f79e8bd7c522
✓ GRANITE (cont, 10 days): 7efd57df-dd49-4b5d-88c0-6de6f8ba9cc1
✓ GRANITE (cont, 15 days): d2837207-5a49-4d00-8042-595dce3e64e1
✓ GRANITE (cont, 21 days): cae8f809-01a3-47bb-8491-cc8d3384856e
✓ GRANITE (cont, 30 days): 1f094878-53cc-4b6b-9b6f-54052c380369
✓ GRANITE (cont, 45 days): 758131ae-8a72-477f-877d-fef531098f24
✓ GRANITE (cont, 60 days): dc2f2b9a-9602-4bed-9bd0-2da8f074d1f2
✓ GRANITE (cont, 90 days): 7bbbcbce-c51c-44ac-a91b-ac5e175ffc50

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ FORD LAKE (alarm, 5 days): 0ba6323f-0c39-4a6e-a7da-f44177cfe5eb
✓ FORD LAKE (alarm, 10 days): 4dd1f77f-02c4-4a95-9ceb-ee020d7299c7
✓ FORD LAKE (alarm, 15 days): 5e18d48c-6d00-460d-9b7c-54a2e0879e5d
✓ FORD LAKE (alarm, 21 days): b2f01d32-3efb-479c-8946-e30b2adc9fb5
✓ FORD LAKE (alarm, 30 days): fd102000-2cc0-4007-abab-daf0a74b99a0
✓ FORD LAKE (alarm, 45 days): 09a3833b-37c0-4f9d-addf-8347510b16d7
✓ FORD LAKE (alarm, 60 days): dd3ab42e-e366-4f7d-9a29-2ad7e49e7dc5
✓ FORD LAKE (alarm, 90 days): 2be79992-e0ba-467f-b61c-a0a9460d4915
✓ FORD LAKE (cont, 5 days): 1a1ef1bf-23f2-4011-9203-1d26de2dabdf
✓ FORD LAKE (cont, 10 days): 3778689d-7a91-4218-b887-0621582c1a45
✓ FORD LAKE (cont, 15 days): 663aa559-8203-436e-894a-158f72013a5d
✓ FORD LAKE (cont, 21 days): e4c1016a-b34e-428d-8ff7-b01b8257f78c
✓ FORD LAKE (cont, 30 days): aa0dc4c8-6799-4c94-b78f-b804b5baafe4
✓ FORD LAKE (cont, 45 days): b1b02247-8e09-4c53-ad62-e4dc1205e291
✓ FORD LAKE (cont, 60 days): 417c0e25-d4d9-4ec5-bd83-42cbe7824e3d
✓ FORD LAKE (cont, 90 days): dc3125b6-953e-40e0-a149-1fb8c2a29f13

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ YUCCA (alarm, 5 days): 17999f4e-a22e-4133-aca4-162e5222425a
✓ YUCCA (alarm, 10 days): 61662094-4563-438f-b165-67f8d00ade9b
✓ YUCCA (alarm, 15 days): e50bb35b-5740-4e89-abc8-366bc008b9d6
✓ YUCCA (alarm, 21 days): b255694c-2dcf-4b60-9f3b-6158f4abd5a7
✓ YUCCA (alarm, 30 days): 789aeafd-e136-4454-9904-df5880b57b37
✓ YUCCA (alarm, 45 days): 44409dd5-a470-4206-9bc3-994849fc618f
✓ YUCCA (alarm, 60 days): 83e461a8-e889-4ce8-81d4-93170bf54a89
✓ YUCCA (alarm, 90 days): 935dcf70-d911-40e9-b133-ab8fcbde25f7
✓ YUCCA (cont, 5 days): 479bcd95-eb3c-4260-9f2e-b71dc2cff431
✓ YUCCA (cont, 10 days): d4021b6a-79e7-4cba-b903-07007d74aeb2
✓ YUCCA (cont, 15 days): d4f2c6ef-5cc3-4bf8-80ba-fa7002241945
✓ YUCCA (cont, 21 days): 3fa73b34-ce29-494e-8264-7c40e1ecac2b
✓ YUCCA (cont, 30 days): aeeeab68-c3ce-4cc5-bbad-b1f6fad19044
✓ YUCCA (cont, 45 days): 0791afd4-bec3-45ae-a317-9fb0ba0237f6
✓ YUCCA (cont, 60 days): 09db06dd-91f8-4704-89f6-6f6bf3276943
✓ YUCCA (cont, 90 days): b760a17b-3fc5-441d-92a0-f3e0a6369455

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ MULHOLLAND (alarm, 5 days): 3091560d-af36-4421-9b62-be0e86e16b05
✓ MULHOLLAND (alarm, 10 days): 353ae86f-3a60-4036-b06d-dde0d177bf3a
✓ MULHOLLAND (alarm, 15 days): 7b1c471c-8c25-4254-88c4-7460eaf7554c
✓ MULHOLLAND (alarm, 21 days): 36cf51c6-d780-4d34-ad6b-5f42c11a4327
✓ MULHOLLAND (alarm, 30 days): 721925b2-6cc2-4994-a5ac-1d65cf333b9a
✓ MULHOLLAND (alarm, 45 days): 485585c7-fac1-4972-b0f3-998e838e86b7
✓ MULHOLLAND (alarm, 60 days): 0ee8c9b9-fd08-441b-9fd3-ec693c6d842a
✓ MULHOLLAND (alarm, 90 days): b82cd269-90b9-42fd-a34e-15707a7f5510
✓ MULHOLLAND (cont, 5 days): d086dddb-d19a-47b7-bde0-bb22b371e4f3
✓ MULHOLLAND (cont, 10 days): feb59c36-1302-4b5a-a53f-7d257f69769f
✓ MULHOLLAND (cont, 15 days): 6bf6b36c-6d29-49bd-9662-65ce1775a777
✓ MULHOLLAND (cont, 21 days): eba0189b-3ba2-4d41-9fa6-f6e42b3c3ec8
✓ MULHOLLAND (cont, 30 days): 670a6e4d-aecf-4ab4-8375-796627d0da7a
✓ MULHOLLAND (cont, 45 days): 84c7a72b-084a-4e5f-bae4-ff7d89a3988d
✓ MULHOLLAND (cont, 60 days): 3c2068e6-abae-4e28-bb6a-bd578a61f0c2
✓ MULHOLLAND (cont, 90 days): d2782f6a-178f-42bf-a5ea-17a49a773f46

/opt/miniconda3/envs/burnseverity/lib/python3.13/site-packages/shapely/constructive.py:246: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(

✓ COAST (alarm, 5 days): a7d4ad31-abe6-44c1-aaee-ca883e6ef01c
✓ COAST (alarm, 10 days): 637c872a-19df-42cb-bdf0-d84a68f88836
✓ COAST (alarm, 15 days): 957b18e1-10bf-47ff-80a0-e1fa39247fe7
✓ COAST (alarm, 21 days): 6c38d611-b053-48f2-bb68-4e01ca7ba43c
✓ COAST (alarm, 30 days): 584a005e-307c-4db9-9358-b5eee797a024
✓ COAST (alarm, 45 days): f6e71754-75c4-451c-9340-e40d4c643599
✓ COAST (alarm, 60 days): 63ce099c-0719-4310-bc65-645ed9ece572
✓ COAST (alarm, 90 days): 02d5d595-ab59-4e67-ba38-32aba392ee24
✓ COAST (cont, 5 days): 31d9c9fa-7b8b-4b97-ad50-db7b109d07f0
✓ COAST (cont, 10 days): cb095b7c-8a23-44c6-808c-1b243373479c
✓ COAST (cont, 15 days): 568a9f54-169d-4f22-a5f2-312e2227df1d
✓ COAST (cont, 21 days): fa62c39a-c860-45db-8b6e-203a7e1e14f6
✓ COAST (cont, 30 days): f9d375f6-8b1e-4638-ae19-d64d0dca1a24
✓ COAST (cont, 45 days): 619ad160-abc5-4419-8b0c-e8cf596d0590
✓ COAST (cont, 60 days): 7da5090a-3b25-48ba-81f8-894c0e83b070
✓ COAST (cont, 90 days): 4c45c0f2-ee87-478f-b167-b616495fc7b2
✓ LIBERTY CANYON (alarm, 5 days): de47ba3c-9e72-401a-a4b2-0841d1ef1927
✓ LIBERTY CANYON (alarm, 10 days): 260c2562-72d8-4481-b062-0f51cf106e3c
✓ LIBERTY CANYON (alarm, 15 days): 0fe8fd8a-d180-40b6-ae4b-ce1700b69649
✓ LIBERTY CANYON (alarm, 21 days): 235c39ff-4e52-4f99-a234-b55fe5e9317c
✓ LIBERTY CANYON (alarm, 30 days): ca7b49f5-67d2-46ed-8d60-30deccc1c5d7
✓ LIBERTY CANYON (alarm, 45 days): 3e80a05e-df19-4628-b47a-0ea23d42fd50
✓ LIBERTY CANYON (alarm, 60 days): 681a1147-737d-471c-8a53-e5338a8caebf
✓ LIBERTY CANYON (alarm, 90 days): 85c1639c-70a6-4db2-a55f-f8772c0bf88a
✓ LIBERTY CANYON (cont, 5 days): 9d023d54-caef-48ee-89e5-a70133484b76
✓ LIBERTY CANYON (cont, 10 days): c521ebd4-d1fb-4641-abc6-931cd680d593
✓ LIBERTY CANYON (cont, 15 days): 6cd493d8-0d52-4094-94ae-a9dbf6cabab3
✓ LIBERTY CANYON (cont, 21 days): b39bdd79-9245-4cc9-9828-e0704dc0f088
✓ LIBERTY CANYON (cont, 30 days): 90bcb475-2340-4554-ad80-b75f7f142799
✓ LIBERTY CANYON (cont, 45 days): e83fb764-852c-4a2a-8847-ca82863c1918
✓ LIBERTY CANYON (cont, 60 days): edcafa48-8fb2-4a37-b50b-e1ab2ee0e01b
✓ LIBERTY CANYON (cont, 90 days): cd82d977-00a4-42e0-acea-4f3d8a4c6aa4

Processed 656 requests. Results saved to fire_processing_jobs.csv

,fire_event_name,job_id,fire_name,date_mode,post_fire_days,status
0,COFFEE POT_date2024-08-03_range5_modealarm,674b9f1e-0dd5-43b6-9717-998a5c8b10e9,COFFEE POT,alarm,5,success
1,COFFEE POT_date2024-08-03_range10_modealarm,36dce962-a982-4e60-af53-eb061e0c6428,COFFEE POT,alarm,10,success
2,COFFEE POT_date2024-08-03_range15_modealarm,7baa9569-e731-4d08-8869-7d2fcdbac731,COFFEE POT,alarm,15,success
3,COFFEE POT_date2024-08-03_range21_modealarm,9b02f9a0-3373-4a8c-8743-1c58ab2f8b5c,COFFEE POT,alarm,21,success
4,COFFEE POT_date2024-08-03_range30_modealarm,eadd650b-94ba-4088-8b3f-9a3666ff4e1b,COFFEE POT,alarm,30,success
...,...,...,...,...,...,...
651,LIBERTY CANYON_date2016-11-05_range21_modecont,b39bdd79-9245-4cc9-9828-e0704dc0f088,LIBERTY CANYON,cont,21,success
652,LIBERTY CANYON_date2016-11-05_range30_modecont,90bcb475-2340-4554-ad80-b75f7f142799,LIBERTY CANYON,cont,30,success
653,LIBERTY CANYON_date2016-11-05_range45_modecont,e83fb764-852c-4a2a-8847-ca82863c1918,LIBERTY CANYON,cont,45,success
654,LIBERTY CANYON_date2016-11-05_range60_modecont,edcafa48-8fb2-4a37-b50b-e1ab2ee0e01b,LIBERTY CANYON,cont,60,success
655,LIBERTY CANYON_date2016-11-05_range90_modecont,cd82d977-00a4-42e0-acea-4f3d8a4c6aa4,LIBERTY CANYON,cont,90,success